repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    exclude: invalid.yaml
  - id: check-json
  - id: check-xml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-merge-conflict
- repo: https://github.com/google/yapf
  rev: 'v0.43.0'
  hooks:
  - id: yapf
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v21.1.8'
  hooks:
  - id: clang-format
    types: [c++, c]
- repo: https://github.com/cpplint/cpplint
  rev: '2.0.2'
  hooks:
  - id: cpplint
    args: ['--filter=-whitespace/line_length,-legal/copyright,-build/include_order,-runtime/references,-build/c++11,-build/c++17,-build/namespaces,-whitespace/indent_namespace']
    exclude: 3rd_party/
